#!/bin/sh

set -e

echo "Download from https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar ..."
curl -LOs https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
chmod +x phpcs.phar
mv phpcs.phar /usr/local/bin/phpcs
