#!/bin/sh

set -e

echo "Download from https://github.com/phpmetrics/PhpMetrics/releases/latest/download/phpmetrics.phar ..."
curl -LOs https://github.com/phpmetrics/PhpMetrics/releases/latest/download/phpmetrics.phar
chmod +x phpmetrics.phar
mv phpmetrics.phar /usr/local/bin/phpmetrics
